export const ALL_SUB_CATEGORY_REQUEST= 'ALL_SUB_CATEGORY_REQUEST'
export const ALL_SUB_CATEGORY_SUCCESS= 'ALL_SUB_CATEGORY_SUCCESS'
export const ALL_SUB_CATEGORY_FAIL= 'ALL_SUB_CATEGORY_FAIL'
export const CLEAR_ERRORS= 'CLEAR_ERRORS'